app = "bot-discord-fvrluq"
primary_region = "cdg"

[build]
dockerfile = "Dockerfile"

[deploy]
release_command = "echo deploy-ok"

[env]
# Le token Discord doit être fourni avec : fly secrets set DISCORD_TOKEN=...

[[vm]]
cpus = 1
memory = "256mb"
size = "shared-cpu-1x"
