app = "bot-discord-fvrluq"
primary_region = "cdg"

[build]
dockerfile = "Dockerfile"

[deploy]
release_command = "echo deploy-ok"

[env]
GUI_AUTOSTART = "1"
GUI_PORT = "3000"

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 3000
min_machines_running = 1

[[vm]]
cpus = 1
memory = "256mb"
size = "shared-cpu-1x"
